### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by SDeGonge** [Glitch3dPenguin/DashyOneLinerForUbuntu#2]
When executing the script, I get the following error...
  install-dashy.sh: line 8: syntax error near unexpected token `newline'
  install-dashy.sh: line 8: `<!DOCTYPE html>'

Any idea what would cause this?
I'm installing it in a Ubuntu 22.10 container in Proxmox.

=====================================================
root@Dashy: wget  https://github.com/Glitch3dPenguin/DashyOneLinerForUbuntu/blob/34e39a68f5756e96ddbc9d02703f36a6503a1b99/install-dashy.sh
--2022-11-13 04:01:35--  https://github.com/Glitch3dPenguin/DashyOneLinerForUbuntu/blob/34e39a68f5756e96ddbc9d02703f36a6503a1b99/install-dashy.sh
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'install-dashy.sh.1'
install-dashy.sh.1                            [ <=>                                                                                 ] 166.80K  --.-KB/s    in 0.1s    
2022-11-13 04:01:35 (1.10 MB/s) - 'install-dashy.sh.1' saved [170803]
root@Dashy: chmod +x install-dashy.sh
root@Dashy: bash install-dashy.sh
install-dashy.sh: line 8: syntax error near unexpected token `newline'
install-dashy.sh: line 8: `<!DOCTYPE html>'

**Comment by Glitch3dPenguin** [comment]
Try removing lines 5-11 and see if it works. 
Or, simply try running `./install-dashy.sh`

**Comment by SDeGonge** [comment]
Same problem if I do that. It seems that the problem lies with the ">" symbol according to a google search on the error message, however, I'm no expert on linux or html.

**Comment by Glitch3dPenguin** [comment]
Cat is trying to create a systemd file to allow the program to start up when your server starts. You are not running the command as a root or sudo user. 

Make sure `sudo bash install-dash.sh`

**Comment by Mierscheid** [comment]
I also have the problem, could you help me with this?
Ubuntu 22.04, Desktop
"./install-dashy.sh
./install-dashy.sh: line 1: syntax error on unexpected word "newline
./install-dashy.sh: line 1: `<!DOCTYPE html>'"

Thanks in advance
With kind regards
Mierscheid

**Comment by Glitch3dPenguin** [comment]
@Mierscheid Make sure you are running the command as sudo or root. To do this on Debian or Ubuntu be sure to run:
`sudo bash install-dash.sh`

**Comment by thevrownguy** [comment]
Same issue here. I tried all of your suggestions above and even spu up another container, Same sytax error.

**Comment by Glitch3dPenguin** [comment]
I will open a container using the latest version of Ubuntu and see if I can tailor this script to work on newer versions. 
Thanks for letting me know there is a problem.

**Comment by ghost** [comment]
Doesent work for any version even 20.10

**Comment by Glitch3dPenguin** [comment]
> When executing the script, I get the following error... install-dashy.sh: line 8: syntax error near unexpected token `newline' install-dashy.sh: line 8: `'
> 
> Any idea what would cause this? I'm installing it in a Ubuntu 22.10 container in Proxmox.
> 
> ===================================================== root@Dashy: wget https://github.com/Glitch3dPenguin/DashyOneLinerForUbuntu/blob/34e39a68f5756e96ddbc9d02703f36a6503a1b99/install-dashy.sh --2022-11-13 04:01:35-- https://github.com/Glitch3dPenguin/DashyOneLinerForUbuntu/blob/34e39a68f5756e96ddbc9d02703f36a6503a1b99/install-dashy.sh Resolving github.com (github.com)... 140.82.113.4 Connecting to github.com (github.com)|140.82.113.4|:443... connected. HTTP request sent, awaiting response... 200 OK Length: unspecified [text/html] Saving to: 'install-dashy.sh.1' install-dashy.sh.1 [ <=> ] 166.80K --.-KB/s in 0.1s 2022-11-13 04:01:35 (1.10 MB/s) - 'install-dashy.sh.1' saved [170803] root@Dashy: chmod +x install-dashy.sh root@Dashy: bash install-dashy.sh install-dashy.sh: line 8: syntax error near unexpected token `newline' install-dashy.sh: line 8: `'

After a lot of testing and playing around with node versions I have determined that Dashy simply does not support Ubuntu 22.10. Please use this script with one of the supported versions of Ubuntu now added to the readme.

**Comment by Glitch3dPenguin** [comment]
> I also have the problem, could you help me with this? Ubuntu 22.04, Desktop "./install-dashy.sh ./install-dashy.sh: line 1: syntax error on unexpected word "newline ./install-dashy.sh: line 1: `'"
> 
> Thanks in advance With kind regards Mierscheid

This was a different issue that has been addressed and fixed. Please try again.

**Comment by Glitch3dPenguin** [comment]
> Same issue here. I tried all of your suggestions above and even spu up another container, Same sytax error.

This was happening due to a different issue that has now been fixed. Please try again.

**Comment by Glitch3dPenguin** [comment]
> Doesent work for any version even 20.10

Dashy is not supported on Ubuntu 20.10 outside of a docker container due to missing and broken nodejs dependencies. This issue has now been fixed with an update to the script. I have also greatly updated the readme to better help the install process.
